[package]
name = "hyprl_supercalc"
version = "0.1.0"
edition = "2021"

[lib]
name = "hyprl_supercalc"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"
ndarray = "0.16"
